//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace RandoPhoto
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int camera_icon = 0x7f020000;
            
            public const int ic_launcher = 0x7f020001;
            
            public const int rando_logo = 0x7f020002;
            
            public const int settings_icon = 0x7f020003;
        }
        
        public sealed class Layouts
        {
            
            public const int login_view = 0x7f030000;
            
            public const int main_view = 0x7f030001;
            
            public const int register_view = 0x7f030002;
        }
        
        public sealed class Colors
        {
            
            public const int background_color = 0x7f040000;
            
            public const int top_panel_color = 0x7f040001;
            
            public const int bottom_panel_color = 0x7f040002;
            
            public const int tab_widget_color = 0x7f040003;
        }
        
        public sealed class Ids
        {
            
            public const int ivLogo = 0x7f050035;
            
            public const int lEmail = 0x7f050036;
            
            public const int etEmail = 0x7f050037;
            
            public const int lPassword = 0x7f050038;
            
            public const int etPassword = 0x7f050039;
            
            public const int btnLogin = 0x7f05003a;
            
            public const int btnRegister = 0x7f05003b;
            
            public const int lNickname = 0x7f05003c;
            
            public const int etNickname = 0x7f05003d;
            
            public const int btnPassword = 0x7f05003e;
        }
        
        public sealed class Strings
        {
            
            public const int app_name = 0x7f060000;
            
            public const int email_text = 0x7f060001;
            
            public const int password_text = 0x7f060002;
            
            public const int login_text = 0x7f060003;
            
            public const int register_text = 0x7f060004;
        }
    }
}
